version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=project_phoera

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
      - consul
    environment:
      - POSTGRES_USER=project_phoera
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
    command: /start-dev.sh

  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=project_phoera
    volumes:
      - .:/app
    links:
      - postgres

  luigi:
    build:
      context: .
      dockerfile: ./compose/luigi/Dockerfile
    volumes:
      - ./luigi:/luigi/tasks
    ports:
      - "8082:8082"
    links:
      - django

  angular:
    build:
      context: .
      dockerfile: ./compose/angular/Dockerfile-dev
    depends_on:
      - consul
    volumes:
      - ./frontend:/var/www/angular
    ports:
      - "3000:3000"
      - "3001:3001"

  consul:
    build:
      context: .
      dockerfile: ./compose/consul/Dockerfile-dev
    volumes:
      - ./consul/config/:/consul/config
    ports:
      - "8500:8500"

  registrator:
    build:
      context: .
      dockerfile: ./compose/registrator/Dockerfile-dev
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul
    command: dockerize -wait http://consul:8500 /start-dev.sh
