FROM node:slim

RUN npm install -g tsd@^0.6.0 typescript@^1.5.0

COPY ./frontend /var/www/angular

WORKDIR /var/www/angular
RUN npm install

COPY ./compose/angular/start-dev.sh /start-dev.sh
RUN chmod +x /start-dev.sh

ENTRYPOINT ["/start-dev.sh"]
